apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-storage-class
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
provisioner: {{ .Values.db.persistence.storageClass.provisioner | quote }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true